#' @rdname norway_nuts3_map_bxxxx_insert_oslo_dt
"norway_xxx_position_title_insert_oslo_b2020_insert_oslo_dt"

#' @rdname norway_nuts3_map_bxxxx_insert_oslo_dt
"norway_xxx_position_title_insert_oslo_b2019_insert_oslo_dt"

#' @rdname norway_nuts3_map_bxxxx_insert_oslo_dt
"norway_xxx_position_title_insert_oslo_b2017_insert_oslo_dt"
